### ISSUE TITLE
Sveltekit template `context was changed to stuff` error  

### ISSUE THREAD

**Issue by YogPanjarale** [magiclabs/create-magic-app#68]
### ✅ Prerequisites

- [ ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?

yes i tried finding it out but i was not able to find similar issue in this repo 

- [ ] Are you running the latest SDK version?

yes , i used `npx make-magic`
- [ ] Are you reporting to the correct repository (`make-magic`)?

yes
### 🐛 Description
Sveltekit demo project not working
it shows error 
![image](https://user-images.githubusercontent.com/64301340/143076983-11228492-5f4d-4a81-b4ac-915e347fc4aa.png)

### 🧩 Steps to Reproduce

1. `npx make-magic`
2.  name it & choose SvelteKit template 
3. `yarn` & `yarn dev`

### 🤔 Expected behavior
it should load the demo project 

### 😮 Actual behavior

[What actually happened? Please include any error stack traces you encounter.]
it did not work it showed this error in browser
![image](https://user-images.githubusercontent.com/64301340/143077154-966487d2-4df7-4fc3-92da-da0288beb586.png)

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software            | Version(s) |
| ------------------- | ---------- |
| `make-magic`        | latest 
| Node                |  v16.13.0
| `yarn`              | 1.22.17
| Operating System    | windows 10

**Comment by Romy01110** [comment]
Ok
